// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3j2_XF5OGzonWf3tGCiMfykZYpO9mnBI',
    appId: '1:71110570899:web:d2f116ed52ec88cba8ae66',
    messagingSenderId: '71110570899',
    projectId: 'socialapp-e7af9',
    authDomain: 'socialapp-e7af9.firebaseapp.com',
    databaseURL: 'https://socialapp-e7af9-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-e7af9.appspot.com',
    measurementId: 'G-HDLJMECM0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDphW5LSrVrv9ivbFVamzQQCZLYmlL1S_I',
    appId: '1:71110570899:android:8640800be4fe4755a8ae66',
    messagingSenderId: '71110570899',
    projectId: 'socialapp-e7af9',
    databaseURL: 'https://socialapp-e7af9-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-e7af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVR3FerN7WkowM8yUXRyk9rcMQGrqNllQ',
    appId: '1:71110570899:ios:93a814b6291a0a9fa8ae66',
    messagingSenderId: '71110570899',
    projectId: 'socialapp-e7af9',
    databaseURL: 'https://socialapp-e7af9-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-e7af9.appspot.com',
    iosClientId: '71110570899-7n1ei0cbfpr7594a9iija5bcfddpmemt.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVR3FerN7WkowM8yUXRyk9rcMQGrqNllQ',
    appId: '1:71110570899:ios:93a814b6291a0a9fa8ae66',
    messagingSenderId: '71110570899',
    projectId: 'socialapp-e7af9',
    databaseURL: 'https://socialapp-e7af9-default-rtdb.firebaseio.com',
    storageBucket: 'socialapp-e7af9.appspot.com',
    iosClientId: '71110570899-7n1ei0cbfpr7594a9iija5bcfddpmemt.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );
}
